#!/bin/sh
set -e

# start renderer
renderd -c /etc/renderd.conf

# Apache gets grumpy about PID files pre-existing
rm -f /usr/local/apache2/logs/httpd.pid

. /etc/apache2/envvars

exec apache2 -DFOREGROUND "$@"
